import type { Metadata } from "next";
import { Inter, Space_Grotesk } from "next/font/google";
import { Header } from "./components/Header";
import LoginModal from "./components/auth/LoginModal";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const grotesk = Space_Grotesk({
  variable: "--font-grotesk",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${grotesk.variable} antialiased`}>
        <Header />
        <main className="mx-auto max-w-5xl px-4 py-6 sm:py-10">
          {children}
        </main>
        <footer className="mt-12 border-t border-[var(--border)] bg-transparent">
          <div className="mx-auto max-w-5xl px-4 py-6 text-sm flex items-center justify-between">
            <span>© {new Date().getFullYear()} haiseven</span>
            <span className="text-gray-500">Web3 gradient minimalism</span>
          </div>
        </footer>
        <LoginModal />
      </body>
    </html>
  );
}
